Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzanames', views.pizzanames, name='pizzanames'),
    path('pizzaname/<int:pizzaname_id>/', views.pizzaname, name='pizzaname'),
    path('comment/<int:pizzaname_id>/', views.comment, name='comment')
]   

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.views.generic import DetailView

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=100)
    pizza_image = models.ImageField(null=True, blank=True, upload_to="images/")
    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()
    def __str__(self):
        return self.topping_name
    
class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.TextField()
    def __str__(self):
        return self.comment

class ImageDisplay(DetailView):
    model = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='upload/')

pizzas/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ["comment"]
        labels = {"comment":"Comments"}

pizzas/views.py
from django.shortcuts import render,redirect
from .models import *
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import DetailView
from .forms import *

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

def pizzanames(request):
    pizzanames = Pizza.objects.order_by('pizza_name')
    context = {'all_pizzas':pizzanames}
    return render(request, 'pizzas/pizzanames.html', context)

def pizzaname(request, pizzaname_id):
    p = Pizza.objects.get(id=pizzaname_id)
    toppings = Topping.objects.filter(pizza=p)
    comments = Comment.objects.filter(pizza=p)
    context = {'pizzaname':p, 'toppings':toppings,'comments':comments}
    return render(request, 'pizzas/pizzaname.html', context)

def comment(request, pizzaname_id):
    pizza = Pizza.objects.get(id=pizzaname_id)
    if request.method != "POST":
        form = CommentForm()
    else:
        print(request.POST)
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            return redirect('pizzas:pizzaname', pizzaname_id=pizzaname_id)
    context = {'form':form, 'pizza':pizza}
    return render(request, "pizzas/comment.html", context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}"> Semi's Pizzeria </a> 
    <a href="{% url 'pizzas:pizzanames' %}"> Delicious Pizzas </a> 
</p>
</p>
{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<a href="{% url 'pizzas:pizzaname' pizza.id %}"> {{ pizza }} </a>
<p> Comment what you think of this delicious pizza: </p>
<form action = "{% url 'pizzas:comment' pizza.id %}" method = "post">
  {% csrf_token %}
  {{form.as_p}}
  <button name ="Submit!">Add comment</button>
</form> 


 

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3"> Welcome to Semi's Pizzeria </h1>
            <p class="lead"> Come eat good food, my friend
            </p>
            <a class="btn btn-lg btn-outline-primary" href="{% url 'pizzas:pizzanames' %}"
            role="button">Select Pizza &raquo;</a>
</div>
{% endblock content %}

pizzas/templates/pizzas/pizzaname.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizzas: {{ pizzaname }} </p>

<ul>

    {% for t in toppings %}
    <li> 
      {{ t.topping_name }}
    </li>

    
    {% endfor %}
</ul>
<ul>
    <img src="{{pizza.pizza_image.url}}" alt="Pizza pic", width="250" height="250">
</ul>
    <a href = "{% url 'pizzas:comment' pizzaname.id %}" > Comment Now </a>

<ul>

  {% for c in comments %}
    <li> 
      {{ c.comment }}
    </li>

    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzanames.html
{% extends "pizzas/base.html" %}
{% block content %}

<p> Here are your Pizzas: </p>

<ul>
    {%  for pizza in all_pizzas %}
    <li>
         <a href="{% url 'pizzas:pizzaname' pizza.id %}"> {{ pizza }} </a>
    </li>
    {% empty %}
        <li> No pizzas have been added yet. </li>
    {% endfor %}

</ul>

{% endblock content %}